server:
  port: 7545
  servlet:
    context-path: /prod

spring:
  data:
    mongodb:
      uri: # Here you can provide production server URL.
      database: # Here you can provide production server database name.
      auto-index-creation: # Here you can provide boolean value.