server:
  port: 9611
  servlet:
    context-path: /dev

spring:
  data:
    mongodb:
#      host: localhost
#      port: 27017
#      username: myjournaluser
#      password: mypassword
      uri: mongodb+srv://golakiyahit1:pq67CrU3EkKwWFiJ@cluster0.byfm5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journalDB
      auto-index-creation: true
  # Security configurations
  # If you want to change default generated username and password than you write below code.
#  security:
#    user:
#      name: john
#      password: 123